### ISSUE TITLE
New function - resize database files

### ISSUE THREAD

**Issue by michalporeba** [dataplat/dbatools#3359]
I'm looking for a function that would allow to manage file size. Something like `Set-DbaDatabaseFile` or `Set-DbaDatabaseFileSize`

As I see it it would be a wrapper around the `alter database [...] modify file` 

In my opinion it would be useful to manually grow files and prevent autogrowth and it might be useful for VLF  management too. It should work with `Get-DbaDatabaseFile`.

Shrinking file doesn't have to be supported, but if it was to be supported I think ti should require something like a `-Force` parameter to prevent accidental shrinking

examples 
1 `Set-DbaDatabaseFile -Database mydb -File mydbfilename -Size 1024` 
this would resize the mydbfilename in mydb database on the localhost to 1GB only if the current size is less than 1GB. If it was already bigger a warning would be displayed explaining how bad shrinking files is and with details about how much of the space is actually used and suggesting use of `-Force` parameter if there is enough of free space in the file to shrink the file.
2 `Set-DbaDatabaseFile -Database mydb -File mydbfilename -Size 1024 -Force`
when the database file size is already greater than 1024MB it would attempt to shrink it to 1024
3 `Set-DbaDatabaseFile -Database mydb -FileType ROW -IncreaseSizeBy 128`
this would add 128 MB to all data files in mydb

4 `Get-DbaDatabaseFile -SqlInstance myinstance | Where { ... } | Set-DbaDatabaseFile -IncreaseSizeBy 128`
That's something I would use to grow files which I think should be grown by 128MB

**Comment by wsmelton** [comment]
I'm up for this command being added. A few notes/points:

- We already have a command that handles shrinking files `Invoke-DbaDatabaseShrink`, so shrinking and the Force command should not be included in this command. 
- The verb `Set` sounds more like you are setting a property(ies) on a given file and not an operation of resizing. I'd say more appropriate command name would be `Invoke-DbaDbFileSize` or maybe just `Invoke-DbaDbResizeFile`. 
- In cases where the size passed in is less than the current size of the file we can just make note of the shrink command in the warning message. 
- An issue to consider is the value you pass in for size, we will have to contend with what unit size is (possibly a parameter for that). Especially if you want to support piping from `Get-DbaDatabaseFile` as it the size property is a `DbaSize` type, so we'd have to ensure we account for the raw value that is output (but not sure what that does in piping on that type).

**Comment by michalporeba** [comment]
I missed the `Invoke-DbaDatabaseShrink` and I agree with the `Invoke-` rather than `Set-` name. But since we have already `*Shrink` I think it would make sense to call this new command `Invoke-DbaDatabaseGrow`. With that change there is really no need nor room for the `-Force` parameter. 

As for the units, I think the MB would be good standard and a good default if we need it to be configurable. I'll check what DbaSize type look like. If we really need to have it configurable we could follow the way the ALTER DATABAE MODIFY FILE works, where you can specify units in the value itself. 

I'll have a look at it tomorrow, create a first draft implementation perhaps.

**Comment by wsmelton** [comment]
Fred and Klaas need to chime in on the command name.

I can see another option of having Set-DbaDbFileGrowth which would handle the auto growth properties of a given file. This would be more inline or match up to what classes in SMO would be used. A resize of a file is changing the growth settings, and if you want to shrink a file with high amount of free space anyway you can't shrink it below the initial file size....so that property has to he changed before you can shrink it.

To grow it you change or set the property as well. So set is likely the good verb to use...just matter coming up with good noun to use.

**Comment by FriedrichWeinmann** [comment]
I think `Set-DbaDbFile` with various options (including growth settings or manual size manipulation) would be the way to go, unless that has too many options and needs to be split from a functionality perspective.

Note on the size input:
I'd go with byte (could use `DbaSize` as input type for that without issues). Reason: PowerShell has a real comfortable way of writing those numbers. Instead of this:
```powershell
Set-DbaDbFile -Database mydb -File mydbfilename -Size 1024
```
you'd write this:
```powershell
Set-DbaDbFile -Database mydb -File mydbfilename -Size 1024MB
```

I can update the class to also accept this input:
```powershell
Set-DbaDbFile -Database mydb -File mydbfilename -Size "1024MB"
```
In case people get confused about strings

**Comment by michalporeba** [comment]
Wouldn't it make sense to keep the names consistent? The _get_ function is `Get-DbaDatabaseFile` so I think it would make sense to keep the full Database word in any _Set_ or _Invoke_ function, or change the _Get_ to be `Get-DbaDbFile`

Thinking about it I like both the ideas with `Set-DbaDatabaseFile` and `Invoke-DbaFileGrowth`. Set command could be used to modify the settings and if the setting is size, then it could trigger growth, that's how SQL Server behaves. But having an `Invoke-DbaFileGrow` would make sense to me too, I would use it to 'manually' grow the file in the maintenance window. That's my original use case

`Get-DbaDatabaseFile | Where { ... } | Invoke-DbaFileGrow`

And that would take the default growth settings and simply grow the file according to the configuration.  It could have an optional parameter to allow calls like 
`Invoke-DbaFileGrow -By 1024MB` or `Invoke-DbaFileGRow -By 10%`

**Comment by FriedrichWeinmann** [comment]
> Wouldn't it make sense to keep the names consistent?

Yepp, but what you don't know yet is that the global decision was to _rename_ all functions with `Database` in their name to `*Db*` and that's just not through yet. `Get-DbaDatabaseFile` will become `Get-DbaDbFile`.

> It could have an optional parameter to allow calls like

Looks like I need to recode the good old number parameter class.

**Comment by michalporeba** [comment]
After thinking about it the `Invoke-DbaDbGrow` to complement the existing `Invoke-DbaDatabaseShrink` might be closer to what I need, so that is where I will start. I still think the `Set-DbaDbFile` might be useful, and I will implement it later too. 

Unless there are any objections I will follow the `Invoke-DbaDatabaseShrink` implementation as much as practical but I think my primary use case will look something like this

`Get-DbaDatabaseFile | Where { ... } | Invoke-DbaDbGrow` where I will expect the files I pipe to `Invoke-DbaDbGrow` to be grown by whatever their configuration is, one increment only. 

`Invoke-DbaDatabaseShrink` is more autonomic. If called on its own with database names it will go and shrink them all. Should I implement it similarly, where one could do something like 
`Invoke-DbaDbGrow -SqlInstance mysqlinstance -Threshold 5%` and all database files which have less than 5% free space will be grown by one increment? 

I'll start with the help comments and parameter with examples of usage I plan to implement it to take the discussion further. Than, if you don't mind, I'll open a PR just to help facilitate the discussion with code examples. I find it easier than constantly sending links to branches

**Comment by michalporeba** [comment]
@FriedrichWeinmann I like your idea to use DbSize so that we can do 
```
Invoke-DbaDbGrow -By 128MB
```

but I would like it to easily work with `Get-DbaDatabaseSpace` which returns objects with properties like `UsedSpaceMB`, `FreeSpaceMB`. Do you guys have any plans to change those parameters to `UsedSpace` and `FreeSpace` respectively and make them use DbSize instead of an int type? If that's the direction in which 1.0 goes I can do the change, but I'd like your advise on how to limit the scope of breaking changes.

**Comment by FriedrichWeinmann** [comment]
I see us going towards using DbaSize wherever possible, especially with the upcoming changes in https://github.com/sqlcollaborative/dbatools/pull/3383 as those significantly improve the user's ability to have control over display style.

Whether to _remove_ existing properties, I'm not so sure - I'd mark that up for 1.0.0 as a switch-over task, rather than do it right now. That way we can administer all the changes in one bitter pill, rather than keep it as a constant issue.

Thus what I'd do right now for code already producing objects with those properties:

 - Add dbasize properties
 - Hide the old *MB properties from the default display
 - Create a `changes-to-do-for-1.0.0.md` file into the project root folder and list it there

**Comment by wsmelton** [comment]
```powershell
    .PARAMETER DatabaseFileSpace
        A list of files as produced by Get-DbaDatabaseFreeSpace which are to be grown

    .PARAMETER Database
        The database(s) to process - this list is auto-populated from the server. If unspecified, all databases will be processed.

    .PARAMETER ExcludeDatabase
        The database(s) to exclude - by default this list is empty

    .PARAMETER AllUserDatabases
        Run command against all user databases only. 

    .PARAMETER FileType
        Specifies the files types that will be grown

            All
                All Data and Log files are grown
            Data
                Just the Data files are grown
            Log
                Just the Log files are grown

    .PARAMETER When 
        Specifies then condition that needs to be met for the file to grow. By default it is set to 10% which means 
        when there is exactly or less free space in the file than 10% of the growth increment then the file will grow. 
        Always the grwoth setting is used to calculate whether the condition is met and the -By parameter is ignored in that regard.
        It can be set to an absolute value like 128MB and then the file will grow if the free space is at or below 128MB. 
        
        "Always" can be passed as value to ensure each file is grown regardless of conditions. Useful when piping files into the function.

    .PARAMETER By 
        Specifies by how much the file should grow. Valid values include 5%, 128MB. By default the By value is not set and the file
        growth configuration will be used to determin by how much it should grow. If no unit is specified bytes are assumed. 

        "Default" can be specified to explicitly use database file configuration.
```

- How do you plan on defining what falls under `AllUserDatabases`?
- `By` and `When` sound more like date parameters or ones used for pulling information based on a date range. Are there better names we can come up with for this functionality? Do you really need a `When` parameter (e.g. if I'm piping data from the space command I can filter it down from there "when" I want the operation, and would likely be the common use: `Get-DbaDatabaseSpace -SqlInstance MyServer | Where-Object PercentUsed -gt 90 | Invoke-DbaDbGrowth...`)
- `By` in the description, you note it will use the increment for growth based on the file auto growth configuration if not provided. Do we really want that ability? If someone has not configured best practices on file growth and has it set to 10% growth, are we going to let that be done? I would require a size/value be provided regardless and not let this command handle any auto growing. It can lead to many mistypes and unecessary headaches.
- `DatabaseFileSpace` this one I would disagree with because it should not be locked down to only allowing piping from `Get-DbaDatabaseSpace` command. I believe @potatoqualitee has been using `InputObject` and based on the type handle getting the needed information/properties from it.
- `FileType` - I would not allow the use of `All` because best practice around file growth you can grow a data file from 50MB to 100GB in one operation. However, doing that with a log file will cause problems in other areas such as VLF count. The operation should be done either with a data file or a log file, but not both.

I believe `Set-DbaDbFile` needs to be written first and not jump the gun on writing command(s) that will end up just having duplicate code and/or end up needing a complete rewrite later down the road. Overall it should be a pretty basic command to write, even if right now it just sets the file size...we can expand that one down the road without breaking changes.

I'm still up in the air on invoking a growth event. Use of Set command to change the file size will ultimately invoke a growth event, I mean that is how you grow a file in increments anyway via T-SQL (e.g. grow a log file from 10MB to 20GB, I'd do that in a set size each time to lessen VLF count).

**Comment by michalporeba** [comment]
Thank you for the detailed critique @wsmelton. 

* How do I define user databases? Those are databases which are not system databases. And system databases are defined here https://docs.microsoft.com/en-us/sql/relational-databases/databases/system-databases
* The above might not be that important. The only reason I have added `AllUserDatabases` parameter was to follow the example of already implemented function, the `Invoke-DbaDatabaseShrink` which has such parameter. To see how it does determine what is a user database I have read the code and it turns out the parameter is not really used internally. I'm happy to remove it from my implementation and list the one in the reference implementation to be removed for 1.0
* By and When have time related meaning, but that is not the only meaning. Out of the two perhaps https://en.oxforddictionaries.com/definition/when has a stronger time connotation but still it is quite natural to say something like 'I will increase the size of the file _when_ there is little free space left'. Perhaps _If_ would be a better word to indicate condition? 
* Do I really need this `When` or `If`? I probably don't. SImilarily to the `AllUSerDatabases` I have added it to make the grow command more in line with what there is already for shrink. My prefered option was piping filtered list of files to be grown, but now I see how perhaps that percentage option could be useful to quickly do things like 
```
Invoke-DbaDbGrow -When 10% -WhatIf
```
which would display the files that need to be grown and by how much and if I don't see any problems with it I could then run the command without `-WhatIf` But if that is against the design principles of dbatools, then I'm happy for it not to be there. I'd just suggest to change the `Invoke-DbaDatabaseShrink`
* As for https://en.oxforddictionaries.com/definition/by I must disagree. It is perfectly natural. `When there is not enough space I will _grow_ my file _by_ 100MB`. I cannot think of a better word. 
* The use of auto growth configuration. For me it is very important, but that is because I'm thinking about using this command not on a single database, but on hundreds or thousands on multiple instances. Those are my databases, and I have configured the auto growth the way I want it, the way they need to be for various reasons so I'm not too concern that suddenly my files will start growing by 10%. This option allows me to grow all the files that need growing, by the pre-configured increment specific to the file in my maintenance window. 
* If you really want to discriminate against clue-less or accidental DBAs I suggest we remove the % option and change the behaviour so it skips (with a warning) any file that is configured to a percentage growth. 
* Do we need the `ALL` option in `FileType`? That's again just a copy from the existing method which I see as analogous. The log files shouldn't need to grow as frequently as data files. If they do, you probably need to think why it is, perhaps the backups are not working? Was it a one of maintenance type of action and it will be better than do a log backup, or wait those few minutes until the next scheduled one instead of growing the file? Perhaps when the files are piped into the grow function it should take any file that somebody piped in? Or should it display warnings when log files are piped to it unless there is `-FileType ANY` (I would probably use _any_ instead of all in that case). But I think there should be a way to use `Invoke-DbaDbGrow` to grow the log file too. 
* I agree the function should take input from not only the `Get-DbaDatabaseSpace` command even though this one seems most natural in my use case and that is why I listed it there. 
* The `FileType` and disallowing _ALL_. What is the harm in this (or using _ANY_ instead in my previous example) if we don't make it the default value (it should be _DATA_) and disallow percentage growth altogether?

I believe in code refactoring which allows me not to believe in the need of having `Set-DbaDbFile` necessarily first. Especially that the scope of `Set-DbaDbFile` is not well defined at the time, and most likely is out of the scope of my original interest that prompted me to work on this. You are right, to start with it might be a pretty basic command and perhaps even it could do it all without the need for `Invoke-DbaDbGrow`, but it was you who argued that the growth should not be implied in a set command (that was your first comment, second point you made). I do agree with you from 6 days ago, and disagree with you yesterday. The `Invoke` verb is better for the file growth. If we implement `Set-DbaDbFile` that does few things like configuring auto growth and then allows to set the file size... well, then perhaps that's a side effect we have to take, but I probably would explain in the documentation that if you want to grow or shrink a file you should use the 'Invoke' commands explicitly and they will change that 'setting' for you. Creating a simply `Set-DbaDbFile` that only grows a file goes completely against it.

**Comment by wsmelton** [comment]
@michalporeba do you still have plans to work on this?

**Comment by michalporeba** [comment]
The short answer is yes, @wsmelton. It's my plan for the next two months to get back into contributing regularly to the project. I want to get back to things I needed, like the `ReadOnly` switch, or this resize, and look at the commands I have problems with. There are few more issues I raised or commented on which are still open, and I will be looking at them all in the coming weeks.

**Comment by tboggiano** [comment]
Is there a code branch for this I might be able to take over and work on this, this will help me out with a presentation I'm doing and replace a SQL script with dbatools?

**Comment by wsmelton** [comment]
@tboggiano I'm not aware of any activity, so you are more than welcome to start working on something if you would like. 

You can create a **draft** PR if you would like to have it reviewed as you work on it.

**Comment by berki7867** [comment]
Hi,

I just wondered if the Invoke-DbaDbGrow was coming soon?
Looks like a good feature.
