### ISSUE TITLE
[Request] - 'sp_SetAutoSAPasswordAndDisable' like command

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8250]
### Summarize Command's Functionality

A security command that would provide the functionality of the undocumented [sp_SetAutoSAPasswordAndDisable](https://www.mssqltips.com/sqlservertip/2006/secure-and-disable-the-sql-server-sa-account/) and more. 

### Is there a command that is similiar or close to what you are looking for?

No

#### Potential features

* Use a random GUID as a "strong" password for `sa`  as [recommended by MS best practices](https://docs.microsoft.com/en-us/sql/sql-server/install/security-considerations-for-a-sql-server-installation?view=sql-server-ver15#strong-passwords).
* Disable the `sa` account. 
* Rename the `sa` account
* Enforce password policy
* More?

#### Other considerations

> But lowlydba, can't you achieve most/all of this with the existing `Set-DbaLogin` command?!

Yup! The command would likely consist mostly of using this existing command + some boilerplate. Since the `sa` has a fixed `sid`, this command would make it easy to target the `sa` even if it had been renamed - it could be included as a one-liner that was safe to run as part of a hardening or at any point in time to validate the desired state of the login. 

Since there is a fair amount of blogging out there about the undocumented stored proc, I think providing a command that is a safer alternative is valuable.

I can likely put up an initial PR for this as it should be straightforward.

**Comment by wsmelton** [comment]
This is more environmental to a given users configuration. We offer commands that can be combined to perform the operation but don't really see a reason it needs to be in the module. It would be something for dbachecks to host IMO (if it doesn't already).

We also do not use undocumented stored procedures because we can't ensure the functionality stays between versions. (We may have a few exceptions but not many.)

If Chrissy wants to include the command it should use command we already have to support the operation.

**Comment by lowlydba** [comment]
Sounds fair. I forget dbachecks exists sometimes 😓
