### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by rickobsitnik** [dataplat/dbatools#8328]
### Summarize Command's Functionality

Any way to debug script blocks of Invoke-Command or a better solution to it so it can be debug? Write-host or Add-Content just isn't enough. This would be a great collection of tools.

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by andreasjordan** [comment]
Have a look at the code of Get-DbaFirewallRule. That might give you an idea how to handle remote debug or verbose output.

https://github.com/dataplat/dbatools/blob/e6997bfc5b472309da6498d6001f1acaf63ae2ce/functions/Get-DbaFirewallRule.ps1#L90-L148

https://github.com/dataplat/dbatools/blob/e6997bfc5b472309da6498d6001f1acaf63ae2ce/functions/Get-DbaFirewallRule.ps1#L156-L161

But let me ask: What would you like to be changed inside of dbatools? I don't see the feature request yet.

**Comment by salvbing** [comment]
I am having issues in Invoke-Program with Update-DbaInstance.  Can I  copy/create my own function Invoke-Program that would be used and I could get into debug there?  
How long is the $ps.WaitForExit() going to wait?

**Comment by andreasjordan** [comment]
You would have to change the code in the module folder before loading the module. Normally, only allcommands.ps1 is loaded, so you have to change that. Better option is to fork the repo to your github account, modify the code there and checkout to the target server. Then import that code, because when the import sees the .git directory, it uses the indivudual files with the commands.

But this goes a bit beond this issue...

About "How long is the $ps.WaitForExit() going to wait?": I don't know, maybe ask on slack.

**Comment by andreasjordan** [comment]
Hi @rickobsitnik - is there anything we can do here? Otherwise I would like to close this issue.

**Comment by salvbing** [comment]
Wish I could set $ps.WaitForExit() to 15 minutes.

**Comment by andreasjordan** [comment]
Ok, here is the doumentation: https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.process.waitforexit?view=net-6.0

So we could use WaitForExit(Int32) to have a timeout. 

But @salvbing - can you open a new feature request for that?

**Comment by andreasjordan** [comment]
I am closing this issue now, but can reopen if there is still the need to discuss this.
