### ISSUE TITLE
Update `Microsoft.Identity.Client.dll` From `4.14` To Newer Version

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8359]
### Summarize Functionality

When importing `dbatools` prior to `MicrosoftPowerBIMgmt` ( uses v`4.25` ) or `PnP.PowerShell` ( uses v`4.36` ), `pwsh` loads the [`4.14` version ](https://github.com/dataplat/dbatools/blob/development/bin/smo/coreclr/Microsoft.Identity.Client.dll)and then I am not able to connect. See [this issue](https://github.com/microsoft/powerbi-powershell/issues/308) on the PowerBI side.

Can we update this one `.dll` or all of `smo`? I read through the [Releases ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases) and didn't see any Breaking Changes.

#### Workaround
I copied the `.dll` from the `MicrosoftPowerBIMgmt.Profile\1.2.1077\lib\netstandard2.0\MSAL\netcoreapp2.1` into `dbatools\1.1.95\bin\smo\coreclr`. The sanity test of opening `pwsh` with my `$PROFILE` loading `dbatools` and then using `Connect-PowerBIServiceAccount` did work.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Not sure what this requires and if it is a package deal for all of the `smo`? If core gets an update would net462 get an update too?

**Comment by andreasjordan** [comment]
Is this still an issue with version 2.0?

**Comment by wsmelton** [comment]
This is not something we can reasonably maintain because we do not keep in sync with what other versions external modules may be using for Microsoft libraries, even SMO can be affected. This library is used for authenticating to Azure AD and easily gets broken in our module.

In this situation, import Power BI's module first and then dbatools and it should still work as you expect.
