### ISSUE TITLE
DBADacOption Bacpac Publish uses invalid typeName Microsoft.SqlServer.Dac.DacImportOptions

### ISSUE THREAD

**Issue by AvdbergDB** [dataplat/dbatools#8369]
### Verified issue does not already exist?

No

### What error did you receive?

I cant use the needed options using dbatools, because the wrong typename is used (importoptions, which have nothing to do with publishing a dacpac or bacpac file!). The correct typename should be DacDeployoptions.
The same error is also present in publish-dbadacpackage:
when used together we get a not so nice error:

$dacoptions  = New-DbaDacOption -Type BACPAC -Action Publish
$dacoptions.DeployOptions.ExcludeObjectTypes = "Users","RoleMembership","Logins"
The property 'ExcludeObjectTypes' cannot be found on this object. Verify that the property exists and can be set.
At line:1 char:1
+ $dacoptions.DeployOptions.ExcludeObjectTypes = "Logins"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The error does not appear when I set the type to DACPAC. But then the deploy won't work either becayse I want to deploy a bacpac, not a dacpac file.

so this won't work either way:
 Publish-DbaDacPackage  -SqlInstance  <instname >-Database  <db> -Path  "C:\bacpac_azure\x.bacpac" -DacOption $dacoptions                                             
       

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$dacoptions  = New-DbaDacOption -Type BACPAC -Action Publish
PS C:\WINDOWS\system32> $dacoptions|gm

   TypeName: Microsoft.SqlServer.Dac.DacImportOptions

$dacoptions  = New-DbaDacOption -Type BACPAC -Action Publish
$dacoptions.DeployOptions.ExcludeObjectTypes = "Users","RoleMembership","Logins"

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1682                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1682                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

azure sql database and sql2017

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04084
Full        4.8.04084
Client      4.0.0.0

**Comment by nvarscar** [comment]
If you check the definition of the DacServices class, you would see that the [ImportBacpac](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.dacservices.importbacpac?view=sql-dacfx-150#microsoft-sqlserver-dac-dacservices-importbacpac(microsoft-sqlserver-dac-bacpackage-system-string-microsoft-sqlserver-dac-dacimportoptions-system-nullable((system-threading-cancellationtoken)))) method requires a DacImportOptions object as a parameter and does not support any other Options objects. As far as I can tell, DacDeployOptions are used in the [Deploy](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.dacservices.deploy?view=sql-dacfx-150) method, which are designed to work with DacPacs only.

Please let me know if I'm missing something here, but otherwise I think what you're asking is not possible. You need to use Bacpac objects (Import/Export) for Bacpacs and Dacpac objects (Export/Publish + apparently Deploy that is not covered in dbatools) for Dacpacs.
