### ISSUE TITLE
Error Importing DBATools Module on Azure Automation account

### ISSUE THREAD

**Issue by kapilswamy** [dataplat/dbatools#8465]
### Verified issue does not already exist?

Yes

### What error did you receive?

Error importing the module dbatools-master. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name dbatools-master, as the module structure was invalid. at Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.ExecuteInternal(CodeActivityContext context, Byte[] moduleContent, String moduleName, ModuleLanguage moduleLanguage) at Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Are you running the latest release?

Yes

### Other details or mentions

I am trying to import DBATools module on Azure automation account and getting error

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

az_6.5.0

### SQL Server Edition and Build number

NA

### .NET Framework Version

NA

**Comment by SQLDBAWithABeard** [comment]
Thanks for this @kapilswamy 

When you say "imported" where are you importing? This piece of information was missing.

It looks like you are trying to import the module from the download from github.

# Method one - from Gallery

What I normally do is

Go to the Module page for the automation account and then Add module and browse the gallery and search for dbatools and install it

![image](https://user-images.githubusercontent.com/6729780/181550108-e6096986-3392-4585-a57a-5c515c2890bf.png)

Once it has imported there

![image](https://user-images.githubusercontent.com/6729780/181548887-0ec695e4-41b9-45b3-8ab3-a004968c2323.png)#

Then it is available in my runbooks - Here I have just run `Get-DbaToolsConfig`

![image](https://user-images.githubusercontent.com/6729780/181550937-7e89c7b3-31e8-4af1-b965-c82f2f63562f.png)

so that method is working for me.

# Method two - using the zip file from GitHub

Now if we remove the module

![image](https://user-images.githubusercontent.com/6729780/181553061-9be2da4d-344d-4027-aa7f-902445cee12b.png)

and download the latest release from 

https://github.com/dataplat/dbatools/releases/tag/v1.1.118

I would always use the official signed release here for this by the way

You can then upload the zip in the same method   

> note - that I updated the module name  <--- This is the important bit

![image](https://user-images.githubusercontent.com/6729780/181561112-6aecd5e3-efaa-4b2a-84d7-f7e521035d04.png)

and once it is imported

![image](https://user-images.githubusercontent.com/6729780/181564377-df8c707e-24ec-43eb-8d57-702fcb39400b.png)

and I can run the test - Again I just ran `Get-DbaToolsConfig`

![image](https://user-images.githubusercontent.com/6729780/181569077-2b2e59e2-4bf1-46b6-851f-2e624cf9c43c.png)

You did not say whether you tried 5.1 or 7  so I did both

![image](https://user-images.githubusercontent.com/6729780/181571123-8acb8ff5-7b36-4b62-91f7-34b3df36a1d8.png)

and 5.1 worked the same way

![image](https://user-images.githubusercontent.com/6729780/181571518-909ecc6f-9270-45d2-a7b5-0de4406c88c4.png)

# Reproducing your error

This lead me to wonder how you were getting the error so I removed the modules again and tried uploading the zip file without altering the module name. 

![image](https://user-images.githubusercontent.com/6729780/181571939-b881b4bc-4449-4569-b71a-66142436158a.png)

and finally I get the same error

![image](https://user-images.githubusercontent.com/6729780/181572041-2fe18929-cc14-40ae-b654-62653206903f.png)


> Error importing the module dbatools-signed. Import failed with the following error:   
> Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name dbatools-signed, as the module structure was invalid. at   
> Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.ExecuteInternal(CodeActivityContext context, Byte[] moduleContent, String moduleName, ModuleLanguage moduleLanguage) at  
 > Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.Execute(CodeActivityContext context) at  
 > System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)  

So the issue is that you should change the name of the module when you import it manually from a zip file - Thi sis referenced in the [Microsoft documentation here ](https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules#author-modules?WT.mc_id=DP-MVP-5002693)

**Comment by jpomfret** [comment]
This is such a great response to an issue 😍😍
