### ISSUE TITLE
Parallel Backup

### ISSUE THREAD

**Issue by rferraton** [dataplat/dbatools#8665]
### Summarize Functionality

Hello everyone,

First I would say I really like all the work done in dbatools, it's really a great framework !

I used to backup "my" databases with Ola Hallengren scripts but I've started to move to dbatools because : 
- dbatools is more flexible 
- dbatools is more easy to deploy
- dbatools is easier to upgrade
- with dbatools I can use an external scheduler to launch backup script and retrieve logs

One feature I like with OH script is the ability to **backup several databases in parallel**. It is not well known and not very easy to implement (several backup jobs are needed)

So my feature request would be to have a new backup function for parallel backup.
I start to work on it, my script use a **powershell 7** **foreach-object -parallel loop** on top of the **Backup-DbaDatabase**

an extract of the script : 
```PowerShell
# A concurrent dictionnary to manage log and returns from parallel backups
$ResultsObjects = [System.Collections.Concurrent.ConcurrentDictionary[string,System.Object]]::new()

$duration=(Measure-Command{

    $SilentdbatoolsResults = $Databases | Sort-Object -Property Size -Descending | ForEach-Object -Parallel {

    $ResultsDict = $using:ResultsObjects #mapped to the $ResultsObjects ConcurrentDictionnary (Thread Safe)
    $Database=$_.Name
    $SqlInstance=$_.SqlInstance
    $BackupDirectory=$using:BackupDirectory
    $FileCount=$using:FileCount
    $BackupType=$using:BackupType

    try {            
            $resbackup = Backup-DbaDatabase -SqlInstance $SqlInstance -Database $Database -Type $BackupType -CompressBackup -Checksum -Verify -FileCount $FileCount -FilePath "${BackupDirectory}\servername\instancename\dbname\backuptype\servername_dbname_backuptype_timestamp.${BackupExtension}" -TimeStampFormat "yyyyMMdd_HHmm" -ReplaceInName -CreateFolder #-ErrorAction Stop -EnableException
            $silentres = $ResultsDict.TryAdd($Database,$resbackup)
        }
        catch  {
            Write-Host "[ERROR] - Backup $BackupType of $Database Failed"
            $silentres=$ResultsDict.TryAdd($Database,$resbackup)
        } 
    } -ThrottleLimit $Degree -TimeoutSeconds $Timeout 
} ).TotalSeconds
        
# Get Results from $ResultsObjects ConcurrentDictionary and find issues
$ResultsCount = $ResultsObjects.Count


$resultinfos = $ResultsObjects.Values | Select-Object ComputerName, InstanceName, Database,Type,Software , Start, End, Duration,TotalSize, CompressedBackupSize, Verified, Backupcomplete, Backupfilescount, BackupPath,Script  | Sort-Object -Property Database
```

I would like to help but I am not as strong as you are for professionnal powershell.

May be you're already work on such a functionnality with the v2.0 ?

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

https://github.com/aetperf/dbatoolsScripts/blob/main/DBA/MSSQL_Backup_All_Databases_In_Parallel.ps1

**Comment by wsmelton** [comment]
@rferraton our module is known to support both PowerShell 7+ and Windows PowerShell. Those users that want to perform backups in parallel have the ability to do that using the backup command from our module and the native features in the version of PowerShell they want to maintain for their environment. We would have to maintain two versions of the command you are speaking of in order to keep the agreement we have with our userbase. I do not see the benefit of that at this time.

The performance you get in PowerShell for parallel operations is subject to the number of objects you are working with and the overhead of those parallel threads in PowerShell. The additional overhead in most cases requires a much higher number of databases to achieve ROI for the work of maintaining the codebase. In my view it is not worth that effort as we generally encourage use of Ola's solution for backups; a primary reason we have commands for both deploying and upgrading the stored procedures.

Our goal in the community is that users, like yourself, can create solutions that utilize our module's code for making things more efficient and achieving their goals in their own environment. The script you have shared helps us in meeting that goal as it provides an example of how our module can be used for an advanced solution with parallel scripting. You are welcome to post it in the Discussions using the 🙌Show and tell category so more users can find it as well.

Closing this for now as no plan to implement. As time goes on and PowerShell and Windows PowerShell balance out it may be something we can look at implementing.

**Comment by wsmelton** [comment]
@rferraton our module is known to support both PowerShell 7+ and Windows PowerShell. Those users that want to perform backups in parallel have the ability to do that using the backup command from our module and the native features in the version of PowerShell they want to maintain for their environment. We would have to maintain two versions of the command you are speaking of in order to keep the agreement we have with our userbase. I do not see the benefit of that at this time.

The performance you get in PowerShell for parallel operations is subject to the number of objects you are working with and the overhead of those parallel threads in PowerShell. The additional overhead in most cases requires a much higher number of databases to achieve ROI for the work of maintaining the codebase. In my view it is not worth that effort as we generally encourage use of Ola's solution for backups; a primary reason we have commands for both deploying and upgrading the stored procedures.

Our goal in the community is that users, like yourself, can create solutions that utilize our module's code for making things more efficient and achieving their goals in their own environment. The script you have shared helps us in meeting that goal as it provides an example of how our module can be used for an advanced solution with parallel scripting. You are welcome to post it in the Discussions using the 🙌Show and tell category so more users can find it as well.

Closing this for now as no plan to implement. As time goes on and PowerShell and Windows PowerShell balance out it may be something we can look at implementing.
