### ISSUE TITLE
Write blog post about encrypting connections using dbatools for 2.0

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8697]
### Summarize Functionality

Please write a blog post that I can reference in the release notes of 2.0.

I believe the
 book touches on it, but the commands that I use are

```
Get-DbaComputerCertificate
New-DbaComputerCertificate
New-DbaComputerCertificateRequest (if infra doesn't allow for New-DbaComputerCertificate)
Set-DbaNetworkCertificate
Enable-DbaForceNetworkEncryption
Test-DbaCertificateExpiration
```

Thanks :bow:

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
Would it be best to have this as a wiki page in the repo? Would allow consistency on knowing the content stays online and we can create a redirect to it from the main site.

**Comment by ACALVETT** [comment]
I can take a first crack at putting a Wiki page together for this, it makes sense as you say to ensure the content stays online.

**Comment by ACALVETT** [comment]
@potatoqualitee  So i borrowed from your book, if that is an issue please let me know and I am happy to redo but below is a first pass. Do you think it needs more meat?  I can do screenshots of the gui as well and talk more but wanted to get some feedback first.

## Introduction

This article will walk you through configuring network certificates for SQL Server.

SQL Server uses the TLS (Transport Layer Security) cryptographic protocol to encrypt the data across a network between the SQL Server instance and the client applications. If you decide to encrypt your SQL Server connections, you will need to obtain a certificate that meets specific conditions. Many conditions are available, so we won’t list them all here, but we will highlight a few of the most important ones along the way.

To explain how TLS will help SQL Server communications be more secure, we’ll refer to Microsoft’s documentation [CertReq](sqlps.io/certreq)

TLS can be used for server validation when a client connection requests encryption. If the instance of SQL Server is running on a computer that has been assigned a certificate from a public certification authority, identity of the computer and the instance of SQL Server is vouched for by the chain of certificates that lead to the trusted root authority. Such server validation requires that the computer on which the client application is running be configured to trust the root authority of the certificate that is used by the server.

Modern clients are now being updated to be secure by default which means that if we do not provision certificates for our SQL Servers you may encounter an error "The target principal name is incorrect" or "The certificate chain was issued by an authority that is not trusted" or "The received certificate has expired". Examples of such updates are:
* Beginning in .NET Framework 4.5 the sqlClient was updated so that, by default TrustServerCertificate is false and Encrypt is true, these settings require a SQL Server certificate.
* Azure Data Studio has the same issue (but not SSMS for now) and the team has written about it here: [Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/connect)

## dbaTools commands

dbaTools provides the following commands to manage the certificate process which we will walk through.

* New-DbaComputerCertificate
* New-DbaComputerCertificateRequest (if infra doesn't allow for New-DbaComputerCertificate)
* Add-DbaComputerCertificate
* Set-DbaNetworkCertificate
* Enable-DbaForceNetworkEncryption
* Test-DbaCertificateExpiration

## Provisioning a new certificate

<strong>Option A </strong>

If your SQL Server is part of an Active Directory domain with its own certificate authority, you can use the command New-DbaComputerCertificate to generate a computer certificate that is appropriate for SQL Server’s use, as shown in the next listing.

Note in both case when populating the DNS list you should provide all DNS aliases, for example with AlwaysOn you must include the listener.

``` Powershell
$splatCert = @{
  ComputerName = "sqlVM1"
  Dns = "sqlVM1.mywork.local", "sqlVM1"
}
New-DbaComputerCertificate $splatCert

ComputerName : SQLVM1
Store        : LocalMachine
Folder       : My
Name         : SQL Server
DnsNameList  : {sqlVM1.mywork.local, sqlVM1}
Thumbprint   : C2C04E463D5699C7CC1A30087445A7C8CAD44842
NotBefore    : 1/9/2023 12:00:00 AM
NotAfter     : 1/9/2025 12:00:00 AM
Subject      : CN=sqlVM1.mywork.local
Issuer       : CN=ad-DC1-CA, DC=mywork, DC=local
Algorithm    : sha256RSA
```

This will both create and install your certificate in the appropriate certificate store. For this command to work, your user account must have permission within Active Directory to create new certificates.

<strong>Option B </strong>

If you do not have permission to create a certificate due to company policy then dbatools can generate a certificate signing request (CSR) for you to give to your PKI administrator for approval. Generating a CSR is also useful when your certificate authority is an external third party such as DigiCert.

``` Powershell
$splatCSR = @{
    ComputerName = "sqlVM1"
    Dns = "sqlVM1.mywork.local", "sqlVM1"
    keylength = 4098
}
 New-DbaComputerCertificateSigningRequest $splatCSR

Directory: C:\Users\dba\Documents\DbatoolsExport\sqlVM1.mywork.local
 
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         1/9/2023  12:00 AM            529 request.inf
-a----         1/9/2023  12:00 AM           1018 sqlvm1.mywork.local.csr
```

## Installing the certificate 

Once you receive a certificate back, follow the instructions provided by the certificate administrator to finish importing your certificate to the Local Machine\My certificate store. A possible option available is to use the following command.

``` Powershell
Add-DbaComputerCertificate -Path C:\temp\cert.cer
```

Next we need to assign the certificate to the SQL Instance.

``` Powershell
Get-DbaComputerCertificate | Out-GridView -PassThru |
    Set-DbaNetworkCertificate -SqlInstance sql1
```

`Set-DbaNetworkCertificate` not only sets the specified certificate, it also goes a step further and adds permissions for the SQL Servers service SID to read the certificate’s private key otherwise SQL Server will not start. Note we add the service SID because if you ever change the service account manually you will not lose access to the certificate. See [Service sids](https://learn.microsoft.com/en-us/sql/relational-databases/security/using-service-sids-to-grant-permissions-to-services-in-sql-server?view=sql-server-ver16).

## Forcing encryption

At this point configuration is complete and clients can specify encryption in their connections but you may want to force all client/server communication to be encrypted, and clients that cannot support encryption (e.g., legacy drivers) are denied access. To achieve this, we need to set the ForceEncryption option to true.

``` Powershell
Enable-DbaForceNetworkEncryption -SqlInstance sql1
```

Once your SQL Server instance has been restarted, your new settings will be in effect and your connections will be encrypted. Although all encryption has a performance impact, network encryption’s impact is negligible, and you will likely not see any difference.


## Managing certificates

Once you have installed your certificates you still need to manage them as eventually they will expire. For this purpose we provide  Test-DbaComputerCertificateExpiration

``` Powershell
 Test-DbaComputerCertificateExpiration 
 
```

## Bringing it all together

``` Powershell 
So the complete script to install a network certificate is below based on requesting a certificate.

$splatCSR = @{
    ComputerName = "sql1"
    Dns = "sql1.ad.local", "sql1"
    keylength = 4098
}
 New-DbaComputerCertificateSigningRequest $splatCSR
##Now give csr to admin and once receive .cer continue.
Add-DbaComputerCertificate -Path C:\temp\cert.cer
Get-DbaComputerCertificate | Out-GridView -PassThru |
    Set-DbaNetworkCertificate -SqlInstance sql1
Enable-DbaForceNetworkEncryption -SqlInstance sql1
```

**Comment by potatoqualitee** [comment]
Nice that'd be cool! I've done it with a cluster but not AGs.

**Comment by potatoqualitee** [comment]
Oh! Just saw the post. Looks great, thank you so much!! Perfect perfect.

**Comment by ACALVETT** [comment]
Excellent!  Glad your happy with it. let me add the AG point and then i will see if i can send it up as a wiki post for you to add to the site.

**Comment by wsmelton** [comment]
@potatoqualitee if you would like contributors to submit content to the GitHub Wiki on this project, we will need to change our configuration to allow it. Right now, only maintainers can push content to the wiki.

![image](https://user-images.githubusercontent.com/11204251/222980272-0315b4a2-9a0a-46a8-bec7-76eac46f0054.png)

**Comment by potatoqualitee** [comment]
Thank you, Shawn. I can add a link to a Discussion on the Wiki -- @ACALVETT can you add a Discussion? That's what I've done in the past, then I just give it a hyperlink (like  https://dbatools.io/docker) 

https://github.com/dataplat/dbatools/discussions/new?category=show-and-tell

That'll get you going in the Show and Tell category 🙏🏼

**Comment by ACALVETT** [comment]
All done
https://github.com/dataplat/dbatools/discussions/8795

**Comment by potatoqualitee** [comment]
Phenomenal! Thank you again 🤩  I will include it around the web.
