### ISSUE TITLE
Invoke-DbaDbUpgrade Issue with SQL Server 2022

### ISSUE THREAD

**Issue by dlh275** [dataplat/dbatools#8825]
I'm on the latest version of dbatools 1.1.145 and get the following error when trying to run Invoke-DbaDbUpgrade on SQL 2022.

Cannot convert value "Version160" to type "Microsoft.SqlServer.Management.Smo.CompatibilityLevel". Error: "Unable to match the identifier name Version160 to a valid enumerator name. 
Specify one of the following enumerator names and try again:
Version60, Version65, Version70, Version80, Version90, Version100, Version110, Version120, Version130, Version140, Version150"
At C:\Users\housedadmin\Documents\WindowsPowerShell\Modules\dbatools\1.1.145\allcommands.ps1:50656 char:93
+ ... lServer.Management.Smo.CompatibilityLevel]"Version$($serverVersion)0"
+                                                         ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : SubstringDisambiguationEnumParseThrewAnException

**Comment by durehed** [comment]
I think this might be because DbaTools 2.0 is not out yet and I know that the Install-DbaInstance cmdlet does not support SQL Server 2022 just yet. It might work in the development branch of DbaTools.
This is of course not for production, but you can try the pre-release if you want:
`Install-Module dbatools -AllowPrerelease`

**Comment by andreasjordan** [comment]
This should be fixed with version 2.0 - so I will close this now. But can reopen if needed.
