### ISSUE TITLE
Export-DbaLogin is slow when there are many users

### ISSUE THREAD

**Issue by csolje** [dataplat/dbatools#8924]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

It takes longer then it should

### Steps to Reproduce

```powershell
Get-DbaLogin -SqlInstance azweunavsql01 | Export-DbaLogin -Path .\NAVTestLogin.sql
```

### Please confirm that you are running the most recent version of dbatools

2.0.0

### Other details or mentions

Get-DbaLogin -SqlInstance azweunavsql01 | Export-DbaLogin -Path .\NAVTestLogin.sql  - takes more then 3 hours which is very unusual. 

I have around 1295 users to export

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU19) (KB5023049) - 15.0.4298.1 (X64)   Jan 27 2023 16:44:09   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 7.0.5

**Comment by wsmelton** [comment]
How many databases across those 1295 users?

**Comment by csolje** [comment]
25

**Comment by wsmelton** [comment]
You state that 3-hour runtime is unusual, how long did it take on previous runs? Was specs of the server different? Did you use an older version of the module (if so what version)?

**Comment by wsmelton** [comment]
Performance issues I'm afraid are difficult to replicate because there are too many environmental factors that can come into play. A local container instance on my machine ran 3k logins in under 10 minutes.

Using Profiler from the run on my machine it gives an example of where it spends the most time. You might run this in your environment to see if that matches up or if code lines are burning more time.

![image](https://github.com/dataplat/dbatools/assets/11204251/61c42def-6d0b-4343-9f99-2b52799bc6bf)

Overall PowerShell pipeline "streaming" is not doable in modules that use SMO like ours. Running Get-DbaLogin to Export command requires that Get command complete before the Export will ever start processing the objects.

**Comment by csolje** [comment]
Okie that makes sense. I was just wondering that the Copy-Dbalogin worked fast, but I guess when I am doing it with Get-DbaLogin then that needs to finish first as you said and then the Export-DbaLogin needs to run after. 

Thank you Shawn for explaining the workings of these two cmdlets. I will close this issue. 

Thanks again
