### ISSUE TITLE
Command to get all functions of a database

### ISSUE THREAD

**Issue by greyforrest** [dataplat/dbatools#9430]
### Summarize Command's Functionality

Would it be possible to add a command to get all functions of a database/database server, in the style of Get-DbaDbStoredProcedures or Get-DbaDbTriggers, just for functions? It should return all functions (table-valued, scalar-valued, aggregate and possibly system functions) maybe with a paramter to exlude system functions. I would use this command to get all functions and then export them via the Export-DbaScript command to possibly apply them on another server or save them as a backup, so the command should return an object that includes the code and is exportable.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by niphlod** [comment]
hi @greyforrest , did you try already with Get-DbaModule ?

**Comment by greyforrest** [comment]
No I didn't, but that should work, thanks for the hint.

**Comment by niphlod** [comment]
Okay, please reopen this if Get-DbaModule isn't up to the task

**Comment by ReeceGoding** [comment]
@greyforrest Did you get this to work? I tried what @niphlod suggested, but I couldn't get it to work.

It seems as if `Get-DbaModule`'s job is to give a table of what has changed rather than give the SMO object. You can pull the `Definition` column from `Get-DbaModule`'s output, but it's just a string and therefore doesn't work with `Export-DbaScript`. I also couldn't find any examples online of these two functions working together successfully.
