### ISSUE TITLE
Invoke-DbaQuery cannot execute query if has GO in multiline comment 

### ISSUE THREAD

**Issue by xabre0** [dataplat/dbatools#9488]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

WARNING: [08:19:19][Invoke-DbaQuery] [SqInstanceExample] Failed during execution | Missing end comment mark '*/'.

### Steps to Reproduce

```powershell
$queryExample = 
"
	/*	
		select 1
		GO		
	*/
	GO
	SELECT 'First select'
	GO
	SELECT 'Second select'
	GO
"

Invoke-DbaQuery -Query $queryExample -SqlInstance "SqInstanceExample"
```

### Please confirm that you are running the most recent version of dbatools

2.1.24

### Other details or mentions

It is the same if I execute with -Query or -File. 
Also, is the same if I use Powershell 5.1 or Powershell 7

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU23) (KB5030333) - 15.0.4335.1 (X64) 
	Sep 21 2023 17:28:44 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor)

### .NET Framework Version

.NET 8.0.8

**Comment by niphlod** [comment]
hi @xabre0 , unfortunately we aren't unable to fix this, as this command is done to process *queries* and not *sqlcmd scripts* .
"simple" GOs are supported, but identifying nested GOs in comments would require us to parse the script completely which is not the agenda of this command (and, an interface that is not supported because *queries* can have parameters, while *sqlcmd script* do not).
To execute *sqlcmd script*s you can use `$database.Query($theContentOfTheScript)` rather than Invoke-DbaQuery.
